[package]
name = "chrome-for-testing"
version = "0.6.0"
edition = "2024"
rust-version = "1.89.0"
repository = "https://github.com/lpotthast/chrome-for-testing"
description = """
Interact with the chrome-for-testing JSON API.
"""
categories = ["web-programming", "development-tools::testing"]
keywords = ["chrome", "chromedriver", "chromium", "selenium", "browser-testing"]
license = "MIT OR Apache-2.0"
readme = "README.md"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]
exclude = [".github/", ".idea/", "AGENTS.md", "Justfile"]

[dependencies]
reqwest = { version = "0.13.2", default-features = false, features = ["json"] }
rootcause = { version = "0.13.0", default-features = false }
serde = { version = "1.0.220", default-features = false, features = ["derive", "std"] }
thiserror = { version = "2.0.5", default-features = false }
time = { version = "0.3.47", default-features = false, features = ["formatting", "parsing", "serde"] }
url = { version = "2.4.0", default-features = false }

[dev-dependencies]
assertr = { version = "0.7.1", default-features = false, features = ["std"] }
mockito = { version = "1.7.2", default-features = false }
reqwest = { version = "0.13.2", default-features = false, features = ["json", "rustls"] }
serde_json = { version = "1.0.151", default-features = false, features = ["alloc"] }
time = { version = "0.3.55", default-features = false, features = ["macros"] }
tokio = { version = "1.53.1", default-features = false, features = ["macros", "rt-multi-thread"] }
